name: Auto Build

env:
  TZ: Asia/Shanghai

on:
    workflow_dispatch:
    schedule:
        - cron: "0 21 * * *"

jobs:
    build-windows:
        name: Build Windows
        runs-on: windows-latest
        steps:
            - name: Setup Git
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Clone Repository
              run: |
                git clone --recursive https://github.com/TurboWarp/desktop C:\turbowarp-desktop
                cd C:\turbowarp-desktop
                git submodule init
                git submodule update

            - name: Install Dependencies
              run: |
                cd C:\turbowarp-desktop
                npm ci
                npm run fetch

            - name: Build
              run: |
                cd C:\turbowarp-desktop
                npm run webpack:prod

            - name: Pack
              run: |
                cd C:\turbowarp-desktop
                npx electron-builder --windows nsis --x64

permissions:
      contents: write












